services:
  caddy:
    image: caddy:2-alpine
    networks:
      - public
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    configs:
      - source: caddyfile_v2
        target: /etc/caddy/Caddyfile
    deploy:
      restart_policy:
        condition: on-failure
          
  api:
    image: ghcr.io/ibrahimothman/notes-app:v1.1.0
    networks:
      - public
      - private
    secrets:
      - db_password
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD_FILE: /run/secrets/db_password
      REDIS_HOST: ${REDIS_HOST}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        max_attempts: 5
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health').read()"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 15s

  db:
    image: postgres:16
    networks:
      - private
    secrets:
      - db_password
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - notes-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  redis:
    image: redis:8.4.2-alpine
    networks:
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s


volumes:
  notes-data:
  caddy-data:
  caddy-config:

networks:
  public:
    driver: overlay
  private:
    driver: overlay
    internal: true

secrets:
  db_password:
    external: true

configs:
  caddyfile_v2:
    file: ./Caddyfile